package release

import (
	"bytes"
	"fmt"
)

// renderLanding builds a minimal static HTML landing page for a release.
// Self-contained, no external assets, no JS — Tor Browser on default
// security renders it perfectly.
func renderLanding(slug string, m manifestT) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="referrer" content="no-referrer">
<title>Release %s</title>
<style>
  body { font: 16px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; max-width: 720px; margin: 2rem auto; padding: 0 1rem; color: #222; background: #fafafa; }
  h1 { font-size: 1.5rem; }
  code, pre { background: #eee; padding: 0 0.3rem; border-radius: 3px; font-size: 0.9em; }
  table { border-collapse: collapse; margin: 1rem 0; width: 100%%; }
  th, td { text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid #ddd; vertical-align: top; }
  .note { background: #fff6d6; border: 1px solid #e5c46b; padding: 1rem; border-radius: 4px; margin: 1rem 0; }
  footer { margin-top: 2rem; color: #777; font-size: 0.9em; border-top: 1px solid #ddd; padding-top: 1rem; }
</style>
</head>
<body>
<h1>Deadman release</h1>
<div class="note">
This archive was published automatically by a deadman's switch. The owner of
the policy failed to check in within their configured window. All material
below was preapproved by the owner for release under these conditions.
</div>

<table>
  <tr><th>Release ID</th><td><code>%s</code></td></tr>
  <tr><th>Released at (UTC)</th><td>%s</td></tr>
  <tr><th>Release mode</th><td>%s</td></tr>
</table>

<h2>Files</h2>
<table>
  <tr><th>Label</th><th>Filename</th><th>Size (bytes)</th><th>SHA-256</th></tr>
`, slug, m.ReleaseID, m.ReleasedAt.Format("2006-01-02 15:04:05"), m.ReleaseMode)

	for _, bb := range m.Bundles {
		label := bb.Label
		if label == "" {
			label = "(unlabeled)"
		}
		fmt.Fprintf(&b, `  <tr><td>%s</td><td><a href="./%s">%s</a></td><td>%d</td><td><code>%s</code></td></tr>`+"\n",
			escape(label), bb.Filename, bb.Filename, bb.SizeBytes, bb.SHA256)
	}

	fmt.Fprintf(&b, `</table>

<h2>Verify</h2>
<p>A signed manifest and detached signature are published alongside the files:</p>
<ul>
  <li><a href="./manifest.json">manifest.json</a> — machine-readable record of this release</li>
  <li><a href="./manifest.sig">manifest.sig</a> — Ed25519 signature over the manifest</li>
</ul>
<p>Service public key (base64url, unpadded):</p>
<pre>%s</pre>

<p>To verify out-of-band:</p>
<pre>curl -s manifest.json | openssl dgst -verify &lt;(echo -n "%s" | base64 -d) -signature manifest.sig -</pre>

<footer>
  Generated by Deadman (open source, self-hostable). Nothing on this page was
  fetched from a third party.
</footer>
</body>
</html>`, m.ServicePubKey, m.ServicePubKey)
	return b.Bytes()
}

// escape is a minimal HTML escaper for label text.
func escape(s string) string {
	r := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '&':
			r = append(r, "&amp;"...)
		case '<':
			r = append(r, "&lt;"...)
		case '>':
			r = append(r, "&gt;"...)
		case '"':
			r = append(r, "&quot;"...)
		case '\'':
			r = append(r, "&#39;"...)
		default:
			r = append(r, s[i])
		}
	}
	return string(r)
}
