#!/usr/bin/env bash
#
# setup-watchdog.sh — install the Tor-aware watchdog on a SEPARATE host.
#
# Run this on the host you've designated as the watchdog (NOT the same
# host that runs deadman-control). On Ubuntu/Debian.
#
# What it does:
#   1. Installs Tor and Go (if missing).
#   2. Builds the verify-watchdog binary from this repo.
#   3. Installs watchdog-poll.sh + verify-watchdog into /usr/local/bin.
#   4. Prompts for: onion URL, pinned service pubkey, alert URL.
#   5. Writes /etc/deadman-watchdog/env (mode 0640).
#   6. Installs and enables the systemd timer (fires every 5 min).
#   7. Performs one immediate poll to confirm the install works.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WD_DIR="${REPO_ROOT}/ops/watchdog-cron"
ENV_DIR="/etc/deadman-watchdog"
ENV_FILE="${ENV_DIR}/env"

if [[ -t 1 ]]; then
  C_GRN=$'\033[32m'; C_YEL=$'\033[33m'; C_RED=$'\033[31m'
  C_BLU=$'\033[34m'; C_BLD=$'\033[1m'; C_RST=$'\033[0m'
else
  C_GRN=""; C_YEL=""; C_RED=""; C_BLU=""; C_BLD=""; C_RST=""
fi
step() { printf "\n%s== %s ==%s\n" "${C_BLU}${C_BLD}" "$1" "${C_RST}"; }
ok()   { printf "  %s✓%s %s\n" "${C_GRN}" "${C_RST}" "$1"; }
warn() { printf "  %s!%s %s\n" "${C_YEL}" "${C_RST}" "$1"; }
fail() { printf "  %s✗ %s%s\n" "${C_RED}" "$1" "${C_RST}" >&2; exit 1; }

ask() {
  local prompt="$1" default="${2:-}" answer=""
  if [[ -n "$default" ]]; then
    read -r -p "    $prompt [$default]: " answer </dev/tty || answer=""
    echo "${answer:-$default}"
  else
    read -r -p "    $prompt: " answer </dev/tty
    echo "$answer"
  fi
}

[[ "$EUID" -eq 0 ]] || fail "Run with sudo."

step "Installing prerequisites"
DEBIAN_FRONTEND=noninteractive apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq tor curl ca-certificates
ok "tor + curl present."
if ! command -v go >/dev/null 2>&1; then
  fail "go is not installed. Install Go (1.25+) and re-run."
fi
ok "go: $(go version)"

step "Building verify-watchdog"
( cd "$WD_DIR/verify-watchdog" && CGO_ENABLED=0 go build -o /usr/local/bin/verify-watchdog . )
chmod 0755 /usr/local/bin/verify-watchdog
install -m 0755 "$WD_DIR/watchdog-poll.sh" /usr/local/bin/watchdog-poll.sh
ok "Installed /usr/local/bin/{verify-watchdog,watchdog-poll.sh}"

step "Configuration"
ONION_URL="$(ask 'Deadman onion URL (e.g. http://abc...onion)')"
[[ -n "$ONION_URL" ]] || fail "Onion URL is required."
echo
echo "    To get the pinned service public key, on the Deadman host run:"
echo "      curl -fsS --socks5-hostname 127.0.0.1:9050 ${ONION_URL%/}/watchdog | jq -r .service_pubkey"
echo "    Or visit /ui/admin/ → Overview after login (it's printed there)."
echo
PUBKEY="$(ask 'Service public key (base64url-unpadded)')"
[[ -n "$PUBKEY" ]] || fail "Service public key is required."
ALERT_URL="$(ask 'Alert URL (POST target on failure; leave blank to log only)')"
ALERT_SECRET=""
if [[ -n "$ALERT_URL" ]]; then
  ALERT_SECRET="$(ask 'Optional shared secret (X-Watchdog-Secret header)' '')"
fi
STALE="$(ask 'Staleness threshold seconds' '300')"

install -d -m 0750 "$ENV_DIR"
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by setup-watchdog.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
WATCHDOG_ONION_URL=${ONION_URL}
WATCHDOG_SERVICE_PUBKEY_B64URL=${PUBKEY}
STALE_THRESHOLD_SECONDS=${STALE}
TOR_SOCKS=127.0.0.1:9050
ALERT_URL=${ALERT_URL}
ALERT_SHARED_SECRET=${ALERT_SECRET}
EOF
chmod 0640 "$ENV_FILE"
ok "Wrote $ENV_FILE."

step "Installing systemd timer"
install -m 0644 "$WD_DIR/deadman-watchdog.service" /etc/systemd/system/deadman-watchdog.service
install -m 0644 "$WD_DIR/deadman-watchdog.timer"   /etc/systemd/system/deadman-watchdog.timer
systemctl daemon-reload
systemctl enable --now deadman-watchdog.timer
ok "Timer enabled (every 5 minutes, persistent across reboots)."

step "Forcing one immediate poll"
if systemctl start deadman-watchdog.service; then
  sleep 2
  if journalctl -u deadman-watchdog.service -n 5 --no-pager | grep -qE 'watchdog OK|^ok'; then
    ok "Initial poll succeeded."
  else
    warn "Initial poll did not succeed; check journalctl -u deadman-watchdog.service"
  fi
fi

cat <<EOF

${C_BLD}${C_GRN}Watchdog installed.${C_RST}

  Status:    systemctl status deadman-watchdog.timer
  Logs:      journalctl -u deadman-watchdog.service -n 50
  Config:    ${ENV_FILE}
  Test:      sudo systemctl start deadman-watchdog.service

  ${C_BLD}Test the alert path now:${C_RST} stop the deadman-control service on
  the other host, wait 5-10 minutes, confirm an alert lands. If it
  doesn't, ALERT_URL or your receiver is misconfigured.

EOF
